### ISSUE TITLE
Calls to the https://maven.sciprog.center/kscience maven repo hangs and times out

### ISSUE THREAD

**Issue by twadzins** [mipt-npm/plotly.kt#105]
https://repo.kotlin.link leads to https://maven.sciprog.center/kscience

However, calls to https://maven.sciprog.center/kscience timeout. I think it's been this way for at least several weeks now as far as I can see.

**Comment by SPC-code** [comment]
repo.koltin.link is unstable today, but seems to be working right now. As for https://maven.sciprog.center/kscience, it works fine. Reposilite does not provide ftp/webdav access, but you can check the availability of specific files like https://maven.sciprog.center/kscience/space/kscience/plotlykt-core/0.7.0/plotlykt-core-0.7.0.jar. Also you can see them directly with reposilite UI: https://maven.sciprog.center/#/kscience/space/kscience/plotlykt-core/0.7.0.

**Comment by twadzins** [comment]
Thanks for the quick followup. After some experimentation, it appears that, for whatever reason, my corporate VPN is blocking access to [https://maven.sciprog.center](https://maven.sciprog.center/kscience), since it works after I hop off the VPN.

I am now able to get to the 0.7.0 libs.

Unfortunantly, I was hoping that would fix an issue I had that starting happening a few weeks ago when the IntelliJ "Kotlin Notebook" plugin got updated. plotly plots no longer render, for instance, using the sample notebook: https://github.com/SciProgCentre/plotly.kt/blob/master/examples/notebooks/plotlykt-demo.ipynb (Modified with ```@file:Repository("https://repo.kotlin.link") @file:DependsOn("space.kscience:plotlykt-jupyter:0.7.0")```)

I just see "A custom header" but no chart. 

This seems like more of a JetBrains issue so I'll start by bringing it up on the Kotlin slack #notebook channel. I'm using IntelliJ Ultimate 2023.3.3 with the plugin version Kotlin Notebook 233.14015.23

Thanks again!

**Comment by SPC-code** [comment]
@twadzins the server for our maven repository is in Russia. So, it is possible that your corporation blocks all traffic from Russia. I will publish all libraries to the maven central. But it takes a lot of time to do maintenance, so I can't promise that I'll do it soon.

As for your problem, please open a separate issue for that. The cause is that Kotlin plugin probably changed the rules for cell output isolation. Please try to call `Plotly.jupyter.notebook()` after loading a library. It switches the renderer into a mode, where plotly js is embeded in each cell. It tremendously increases the notebook file size but should work even with cell isolation.
