### ISSUE TITLE
No plot in runnning dynamicServer.kt

### ISSUE THREAD

**Issue by holgerbrandl** [mipt-npm/plotly.kt#58]
I've checked out the repo, imported it into Intellij as gradle project. When running the dynamicServer.kt, it starts up correctly, but the plot is missing:

![image](https://user-images.githubusercontent.com/200952/103710462-5e9db200-4fb5-11eb-8832-a0e8b1cb4c4a.png)

Judging from the sources I'd expect some sinus/cosinus action to happen.

**Comment by altavir** [comment]
Hi @holgerbrandl. Thanks for reporting. I spent some time on this but forgot to file an issue. This is actually an IDEA bug (regression): https://youtrack.jetbrains.com/issue/KT-44101 (please vote it up). Everything works fine with gradle, but Idea does not correctly load transitive resources and thus it does not load the plotly JS bundle.

In order to fix that, you need to create a gradle runner for the specific file: https://github.com/mipt-npm/plotly.kt/blob/55aa19038cb5609c367302f5d1e20607f0f2d30a/examples/build.gradle.kts#L32-L36

**Comment by altavir** [comment]
Actually, the workaround is rather simple and does not break anything, so I added it to the dev branch: https://github.com/mipt-npm/plotly.kt/blob/732d66ea7d709ea7fd232aaec4e90159ff990fa7/examples/build.gradle.kts#L34-L40. Everything should work fine in `dev` now.

**Comment by holgerbrandl** [comment]
Thanks @altavir for the kind support. The example works great from within the IDE with the 2nd workaround. 

I've upvoted the KT-issue. I also run into gradle vs ide inconsistencies multiple times more recently and it is always very confusing/annoying.

**Comment by altavir** [comment]
Published in 0.3.1
