### ISSUE TITLE
Bintray sunset

### ISSUE THREAD

**Issue by tonicsoft** [mipt-npm/plotly.kt#71]
I learned today, via usage of this project, that Bintray will be unavailable soon.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

In case you are in the same position as me and managed to miss any advance warning, I thought I would give you a heads up as it may mean this project will not be usable anymore.

I have fixed my builds by using the workaround suggested in #66 (with version 1.7.7 of kotlin-logging) and that has allowed me to access all of the dependencies again.

I'm not sure where I'm actually getting the project artefacts now though, I think Jcenter. If I understand correctly they will continue to be available there for 1 year.

**Comment by altavir** [comment]
Thanks for the reminder. The next version of the whole kscience library set will be hosted on mavenCentral (it is already working for KMath). Dev versions are hosted in a JetBrains Space instance and are accessible through https://repo.kotlin.link/. I will try to make all releases ASAP, but this is not a fast process since we need to review a lot of code.

**Comment by altavir** [comment]
0.4.0 just released without dependencies on bintray libraries.
